### ISSUE TITLE
error bug

### ISSUE THREAD

**Issue by ucasiggcas** [johnny12150/GCE-GNN#4]
hi
在处理数据中，也就是这个**MultiSessionsGraph**类中，出现这种情况是咋回事啊？
咋解决啊，大佬指点下啊，多谢

```
Processing...

Traceback (most recent call last):
  File "mymain.py", line 83, in <module>
    main()
  File "mymain.py", line 36, in main
    train_dataset = MultiSessionsGraph(cur_dir + '/datasets/' + opt.dataset, phrase='train')
  File "/data1/xulm1/GCE-GNN/pytorch_code/graph_loader.py", line 15, in __init__
    super(MultiSessionsGraph, self).__init__(root, transform, pre_transform)
  File "/home/xulm1/anaconda3/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "/home/xulm1/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 92, in __init__
    self._process()
  File "/home/xulm1/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 165, in _process
    self.process()
  File "/data1/xulm1/GCE-GNN/pytorch_code/graph_loader.py", line 31, in process
    data = pickle.load(open(self.root + '/' + self.raw_file_names[0], 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/data1/xulm1/GCE-GNN/pytorch_code/datasets/diginetica/train.txt'
```

**Comment by johnny12150** [comment]
Since the code is modified from the `SR-GNN` repo, you should run the `main.py` under the folder `pytorch_code`.
