### ISSUE TITLE
error bug again

### ISSUE THREAD

**Issue by ucasiggcas** [johnny12150/GCE-GNN#5]
```
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    main()
  File "main.py", line 47, in main
    train_dataset = MultiSessionsGraph(cur_dir + '/datasets/' + opt.dataset, phrase='train', opt=opt)
TypeError: __init__() got an unexpected keyword argument 'opt'
```

**Comment by ucasiggcas** [comment]
and I use the SRGNN pytorch code,
the codes again error
```
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    main()
  File "main.py", line 47, in main
    train_dataset = MultiSessionsGraph(cur_dir + '/datasets/' + opt.dataset, phrase='train')
  File "/data/logs/xulm1/SR-GNN/pytorch_code/graph_loader.py", line 15, in __init__
    super(MultiSessionsGraph, self).__init__(root, transform, pre_transform)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 92, in __init__
    self._process()
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 165, in _process
    self.process()
  File "/data/logs/xulm1/SR-GNN/pytorch_code/graph_loader.py", line 31, in process
    data = pickle.load(open(self.root + '/' + self.raw_file_names[0], 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/data/logs/xulm1/SR-GNN/pytorch_code/datasets/diginetica/train.txt'
```

**Comment by ucasiggcas** [comment]
this is the biggest bug !

**Comment by ucasiggcas** [comment]
and solved the up,comes the down
```
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    main()
  File "main.py", line 61, in main
    model = trans_to_cuda(SessionGraph(opt, n_node))
  File "/data/logs/xulm1/SR-GNN/pytorch_code/model.py", line 116, in __init__
    self.global_data = torch.load('../datasets/'+opt.dataset+'/global_graph_start0.pt')
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/diginetica/global_graph_start0.pt'
```

**Comment by ucasiggcas** [comment]
where is the file? **global_graph_start0.pt**

**Comment by johnny12150** [comment]
> where is the file? **global_graph_start0.pt**

You need to run `build_global_graph.py` to generate it.
As mentioned in [below](https://github.com/johnny12150/GCE-GNN/issues/1#issuecomment-722884672).
I will add a simple doc to explain the workflow sooner.
